site_name: MarketGod Trading Documentation
site_url: http://documentation.marketgod.io   
nav:
    - Home: index.md
    - About: about.md
    - Recents: recents.md
    - FAQ: faq.md
theme: 
    name: gitbook 
